apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard 

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: model-trainer-job
spec:
  # Programado para ejecutarse cada 1 minuto
  schedule: "*/1 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 600
      template:
        metadata:
          labels:
            app: model-trainer
        spec:
          containers:
          - name: model-trainer
            # Tu imagen de Docker Hub
            image: diegomarceloap/model-trainer:1.0.0
            volumeMounts:
            - name: model-volume
              mountPath: /shared-volume
          volumes:
          - name: model-volume
            persistentVolumeClaim:
              claimName: model-pvc
          terminationGracePeriodSeconds: 30
          restartPolicy: OnFailure